# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoFxD0vh-kJjAsMFtX1PpLsLPNvnc10W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

df = pd.read_csv("Advertising.csv")

print(df.head())

print(df.isnull().sum())

df.dropna(inplace=True)

X = df[['TV', 'Radio', 'Newspaper']]

y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales")

plt.show()


# -----------------------------------
# VISUALIZATION 2
# TV Advertising vs Sales
# -----------------------------------

plt.figure(figsize=(8,5))

plt.scatter(df['TV'], df['Sales'])

plt.xlabel("TV Advertising Spend")
plt.ylabel("Sales")
plt.title("TV Advertising Impact on Sales")

plt.show()


# -----------------------------------
# VISUALIZATION 3
# Radio Advertising vs Sales
# -----------------------------------

plt.figure(figsize=(8,5))

plt.scatter(df['Radio'], df['Sales'])

plt.xlabel("Radio Advertising Spend")
plt.ylabel("Sales")
plt.title("Radio Advertising Impact on Sales")

plt.show()


# -----------------------------------
# VISUALIZATION 4
# Social Media Advertising vs Sales
# -----------------------------------

plt.figure(figsize=(8,5))

plt.scatter(df['Newspaper'], df['Sales'])

plt.xlabel("Newspaper Advertising Spend")
plt.ylabel("Sales")
plt.title("Newspaper Advertising Impact on Sales")

plt.show()